#!/bin/sh
# Bypass Proxy installer for OpenWrt (generated by build.sh - do not edit by hand)

[ "$(id -u)" = 0 ] || {
    echo "Run as root"
    exit 1
}

echo "== Installing Bypass Proxy =="

# ============================================================
# DEPENDENCIES (installed only if missing)
# ============================================================

if [ ! -x /usr/sbin/redsocks ]; then
    echo "Installing redsocks..."
    apk update >/dev/null 2>&1
    apk add redsocks || {
        echo "ERROR: cannot install redsocks"
        exit 1
    }
fi

if ! command -v iptables >/dev/null 2>&1; then
    echo "Installing iptables-nft..."
    apk add iptables-nft kmod-ipt-nat iptables-mod-nat-extra kmod-ipt-nat-extra ||
    apk add iptables-nft kmod-ipt-nat || {
        echo "ERROR: cannot install iptables dependencies"
        exit 1
    }
fi

if [ ! -f /usr/lib/lua/luci/cbi.lua ]; then
    echo "Installing luci-compat..."
    apk add luci-compat || {
        echo "WARNING: luci-compat could not be installed."
        echo "The proxy service will still work, but the LuCI page may not."
    }
fi

mkdir -p /etc/config /etc/init.d /usr/lib/lua/luci/controller /usr/lib/lua/luci/model/cbi

# ============================================================
# UCI CONFIG (an existing configuration is never overwritten)
# ============================================================

if [ -f /etc/config/bypass_proxy ]; then
    echo "Keeping existing /etc/config/bypass_proxy"
else
cat > /etc/config/bypass_proxy <<'BP_UCI'
# Bypass Proxy - fill in Proxy Server and at least one Destination,
# either in LuCI (Services -> Bypass Proxy) or with uci, e.g.:
#   uci set bypass_proxy.main.server='proxy.example.com'
#   uci add_list bypass_proxy.main.destination='203.0.113.5'
#   uci commit bypass_proxy
config proxy 'main'
    option server ''
    option port '1080'
    option type 'socks5'
    option local_port '1337'
BP_UCI
fi

# ============================================================
# INIT SCRIPT
# ============================================================

cat > /etc/init.d/bypass-proxy <<'BP_INIT'
#!/bin/sh /etc/rc.common
# Bypass Proxy - selective TCP SOCKS4/SOCKS5 proxy for OpenWrt
# LAN TCP -> iptables-nft nat PREROUTING -> chain BYPASS_PROXY -> REDIRECT -> Redsocks -> SOCKS server

USE_PROCD=1

START=99
STOP=10

SVC="bypass-proxy"
CONFIG="bypass_proxy"
SECTION="main"

REDSOCKS_BIN="/usr/sbin/redsocks"
REDSOCKS_CONF="/etc/redsocks-bypass.conf"

CHAIN="BYPASS_PROXY"
TEST_CHAIN="BYPASS_PROXY_TEST"

LAN_IF="br-lan"

REDIRECT_TRIES=10

ipt()
{
    iptables -w "$@"
}

log_msg()
{
    logger -t "$SVC" -p daemon.info "$*"
}

err()
{
    logger -t "$SVC" -p daemon.err "$*"
    echo "$SVC: $*" >&2
}

is_running()
{
    ubus call service list "{\"name\":\"$SVC\"}" 2>/dev/null |
        jsonfilter -e "@[\"$SVC\"].instances.main.running" 2>/dev/null |
        grep -qx true
}

# ============================================================
# VALIDATION
# ============================================================

valid_ipv4()
{
    local ip="$1"
    local a b c d
    local oldifs="$IFS"

    case "$ip" in
        ''|*[!0-9.]*|.*|*.|*..*)
            return 1
            ;;
    esac

    IFS=.
    set -- $ip
    IFS="$oldifs"

    [ "$#" -eq 4 ] || return 1

    a="$1"
    b="$2"
    c="$3"
    d="$4"

    for octet in "$a" "$b" "$c" "$d"; do
        [ -n "$octet" ] || return 1
        [ "${#octet}" -le 3 ] || return 1

        case "$octet" in
            0?*)
                return 1
                ;;
        esac

        [ "$octet" -le 255 ] 2>/dev/null || return 1
    done

    return 0
}

valid_port()
{
    case "$1" in
        ''|*[!0-9]*)
            return 1
            ;;
    esac

    [ "$1" -ge 1 ] 2>/dev/null || return 1
    [ "$1" -le 65535 ] 2>/dev/null || return 1

    return 0
}

valid_dest()
{
    local ip
    local prefix

    case "$1" in
        */*)
            ip="${1%%/*}"
            prefix="${1#*/}"

            valid_ipv4 "$ip" || return 1

            case "$prefix" in
                ''|*[!0-9]*)
                    return 1
                    ;;
            esac

            [ "$prefix" -ge 1 ] 2>/dev/null || return 1
            [ "$prefix" -le 32 ] 2>/dev/null || return 1

            return 0
            ;;

        *)
            valid_ipv4 "$1"
            ;;
    esac
}

valid_server()
{
    case "$1" in
        ''|*[!A-Za-z0-9.-]*|-*|.*|*-|*.|*..*)
            return 1
            ;;
    esac

    return 0
}

valid_cred()
{
    [ "${#1}" -le 255 ] || return 1

    [ "$(printf '%s' "$1" | tr -d '\000-\037\177')" = "$1" ]
}

escape_redsocks()
{
    printf '%s' "$1" |
        sed \
            -e 's/\\/\\\\/g' \
            -e 's/"/\\"/g'
}

# ============================================================
# LOAD CONFIGURATION
# ============================================================

add_dest()
{
    local destination="$1"

    [ -n "$destination" ] || return 0

    if ! valid_dest "$destination"; then
        BAD_DEST="$BAD_DEST $destination"
        return 0
    fi

    case " $DESTS " in
        *" $destination "*)
            return 0
            ;;
    esac

    DESTS="$DESTS $destination"
}

load_settings()
{
    DESTS=""
    BAD_DEST=""

    config_load "$CONFIG"

    config_get SERVER \
        "$SECTION" server ""

    config_get PORT \
        "$SECTION" port "1080"

    config_get TYPE \
        "$SECTION" type "socks5"

    config_get LOCAL_PORT \
        "$SECTION" local_port "1337"

    config_get USERNAME \
        "$SECTION" username ""

    config_get PASSWORD \
        "$SECTION" password ""

    config_list_foreach \
        "$SECTION" destination add_dest

    TYPE="$(printf '%s' "$TYPE" | tr 'A-Z' 'a-z')"
}

validate_settings()
{
    case "$TYPE" in
        socks5|socks4)
            ;;
        *)
            err "invalid proxy type '$TYPE' (only socks5 or socks4)"
            return 1
            ;;
    esac

    [ -n "$SERVER" ] || {
        err "no proxy server configured (LuCI: Services -> Bypass Proxy)"
        return 1
    }

    valid_server "$SERVER" || {
        err "invalid proxy server '$SERVER'"
        return 1
    }

    valid_port "$PORT" || {
        err "invalid proxy port '$PORT'"
        return 1
    }

    valid_port "$LOCAL_PORT" || {
        err "invalid local redirect port '$LOCAL_PORT'"
        return 1
    }

    [ -z "$BAD_DEST" ] || {
        err "invalid proxy destination(s):$BAD_DEST"
        return 1
    }

    [ -n "$DESTS" ] || {
        err "no proxy destinations configured (LuCI: Services -> Bypass Proxy)"
        return 1
    }

    valid_cred "$USERNAME" || {
        err "invalid username"
        return 1
    }

    valid_cred "$PASSWORD" || {
        err "invalid password"
        return 1
    }

    return 0
}

# ============================================================
# REDSOCKS CONFIG
# ============================================================

write_conf()
{
    local tmp="${REDSOCKS_CONF}.new"
    local old_umask
    local rc
    local out

    old_umask="$(umask)"
    umask 077

    {
        printf 'base {\n'
        printf '\tlog_debug = off;\n'
        printf '\tlog_info = on;\n'
        printf '\tlog = "syslog:daemon";\n'
        printf '\tdaemon = off;\n'
        printf '\tredirector = iptables;\n'
        printf '}\n\n'

        printf 'redsocks {\n'
        printf '\tlocal_ip = 0.0.0.0;\n'
        printf '\tlocal_port = %s;\n' "$LOCAL_PORT"
        printf '\tip = "%s";\n' "$(escape_redsocks "$SERVER")"
        printf '\tport = %s;\n' "$PORT"
        printf '\ttype = %s;\n' "$TYPE"

        if [ -n "$USERNAME" ]; then
            printf '\tlogin = "%s";\n' \
                "$(escape_redsocks "$USERNAME")"
        fi

        if [ -n "$PASSWORD" ] && [ "$TYPE" = "socks5" ]; then
            printf '\tpassword = "%s";\n' \
                "$(escape_redsocks "$PASSWORD")"
        fi

        printf '}\n'

    } > "$tmp"

    rc=$?

    umask "$old_umask"

    [ "$rc" -eq 0 ] || {
        rm -f "$tmp"
        return 1
    }

    chmod 600 "$tmp" || {
        rm -f "$tmp"
        return 1
    }

    out="$("$REDSOCKS_BIN" -t -c "$tmp" 2>&1)" || {
        echo "$out" >&2
        rm -f "$tmp"
        return 1
    }

    mv -f "$tmp" "$REDSOCKS_CONF"
    chmod 600 "$REDSOCKS_CONF"

    return 0
}

# ============================================================
# KERNEL MODULES / REDIRECT
# ============================================================

load_modules()
{
    modprobe nf_nat >/dev/null 2>&1 || true
    modprobe nft_compat >/dev/null 2>&1 || true
    modprobe iptable_nat >/dev/null 2>&1 || true
    modprobe xt_REDIRECT >/dev/null 2>&1 || true
}

remove_test_chain()
{
    ipt -t nat -F "$TEST_CHAIN" >/dev/null 2>&1 || true
    ipt -t nat -X "$TEST_CHAIN" >/dev/null 2>&1 || true
}

redirect_ready()
{
    local attempt=1

    while [ "$attempt" -le "$REDIRECT_TRIES" ]; do

        load_modules

        remove_test_chain

        if ipt -t nat -N "$TEST_CHAIN" >/dev/null 2>&1 &&
           ipt -t nat -A "$TEST_CHAIN" \
                -p tcp \
                -d 192.0.2.1 \
                -j REDIRECT \
                --to-ports "$LOCAL_PORT" >/dev/null 2>&1
        then
            remove_test_chain
            return 0
        fi

        remove_test_chain

        log_msg "REDIRECT target not ready: attempt $attempt/$REDIRECT_TRIES"

        sleep 2

        attempt=$((attempt + 1))
    done

    return 1
}

# ============================================================
# FIREWALL
# ============================================================

fw_remove()
{
    local n=0

    while [ "$n" -lt 20 ] &&
          ipt -t nat -D PREROUTING \
              -i "$LAN_IF" \
              -p tcp \
              -j "$CHAIN" >/dev/null 2>&1
    do
        n=$((n + 1))
    done

    ipt -t nat -F "$CHAIN" >/dev/null 2>&1 || true
    ipt -t nat -X "$CHAIN" >/dev/null 2>&1 || true

    remove_test_chain

    return 0
}

fw_install()
{
    local destination

    fw_remove

    ipt -t nat -N "$CHAIN" || {
        err "cannot create $CHAIN"
        return 1
    }

    for destination in $DESTS; do

        ipt -t nat -A "$CHAIN" \
            -p tcp \
            -d "$destination" \
            -j REDIRECT \
            --to-ports "$LOCAL_PORT" || {
                err "failed to add REDIRECT rule for $destination"
                fw_remove
                return 1
            }

    done

    ipt -t nat -I PREROUTING 1 \
        -i "$LAN_IF" \
        -p tcp \
        -j "$CHAIN" || {
            err "failed to attach $CHAIN to PREROUTING"
            fw_remove
            return 1
        }

    for destination in $DESTS; do

        ipt -t nat -C "$CHAIN" \
            -p tcp \
            -d "$destination" \
            -j REDIRECT \
            --to-ports "$LOCAL_PORT" >/dev/null 2>&1 || {
                err "REDIRECT rule missing for $destination"
                fw_remove
                return 1
            }

    done

    return 0
}

# ============================================================
# PROCD SERVICE
# ============================================================

start_service()
{
    load_settings

    validate_settings || return 1

    [ -x "$REDSOCKS_BIN" ] || {
        err "$REDSOCKS_BIN not found"
        return 1
    }

    write_conf || {
        err "failed to generate Redsocks configuration"
        return 1
    }

    redirect_ready || {
        err "iptables REDIRECT target unavailable"
        return 1
    }

    fw_install || {
        err "firewall installation failed"
        return 1
    }

    procd_open_instance main

    procd_set_param command \
        "$REDSOCKS_BIN" \
        -c "$REDSOCKS_CONF"

    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance

    log_msg "started"
}

stop_service()
{
    fw_remove
    log_msg "stopped"
}

reload_service()
{
    if is_running; then
        stop
        start
    fi
}

service_triggers()
{
    procd_add_reload_trigger "$CONFIG"
}
BP_INIT

chmod +x /etc/init.d/bypass-proxy

# ============================================================
# LUCI CONTROLLER
# ============================================================

cat > /usr/lib/lua/luci/controller/bypass_proxy.lua <<'BP_CTL'
module("luci.controller.bypass_proxy", package.seeall)

function index()
    if not nixio.fs.access("/etc/config/bypass_proxy") then
        return
    end

    local e = entry(
        {"admin", "services", "bypass_proxy"},
        cbi("bypass_proxy"),
        _("Bypass Proxy"),
        60
    )

    e.dependent = false
end
BP_CTL

# ============================================================
# LUCI PAGE
# ============================================================

cat > /usr/lib/lua/luci/model/cbi/bypass_proxy.lua <<'BP_CBI'
local sys = require "luci.sys"
local util = require "luci.util"

local INIT = "/etc/init.d/bypass-proxy"

local m = Map(
    "bypass_proxy",
    translate("Bypass Proxy"),
    translate(
        "Selective TCP proxy. Only configured IPv4 destinations " ..
        "are sent through the SOCKS proxy."
    )
)

local s = m:section(
    NamedSection,
    "main",
    "proxy",
    translate("Bypass Proxy")
)

s.anonymous = true
s.addremove = false

-- ============================================================
-- SERVICE HELPERS
-- ============================================================

local function running()
    local result = sys.exec(
        "ubus call service list '{\"name\":\"bypass-proxy\"}' " ..
        "2>/dev/null | " ..
        "jsonfilter -e '@[\"bypass-proxy\"].instances.main.running' " ..
        "2>/dev/null"
    )

    return util.trim(result or "") == "true"
end

local function boot_enabled()
    return sys.call(
        INIT .. " enabled >/dev/null 2>&1"
    ) == 0
end

local function service_action(action)
    sys.call(
        INIT .. " " .. action .. " >/dev/null 2>&1"
    )
end

-- IPv4 / IPv4 CIDR validation (same rules as the init script)
local function ipv4(str)
    local a, b, c, d = str:match("^(%d+)%.(%d+)%.(%d+)%.(%d+)$")

    if not a then
        return false
    end

    for _, oct in ipairs({ a, b, c, d }) do
        if #oct > 3 or tonumber(oct) > 255 or
           (#oct > 1 and oct:sub(1, 1) == "0") then
            return false
        end
    end

    return true
end

local function destination_ok(str)
    local ip, prefix = str:match("^([%d%.]+)/(%d+)$")

    if ip then
        return ipv4(ip) and
               #prefix <= 2 and
               prefix:sub(1, 1) ~= "0" and
               tonumber(prefix) <= 32
    end

    return ipv4(str)
end

-- ============================================================
-- STATUS
-- ============================================================

local status = s:option(
    DummyValue,
    "_status",
    translate("Status")
)

function status.cfgvalue()
    if running() then
        return translate("Running")
    end

    return translate("Stopped")
end

-- ============================================================
-- START / STOP
-- ============================================================

local toggle = s:option(
    Button,
    "_toggle",
    translate("Service")
)

function toggle.render(self, section, scope)
    if running() then
        self.inputtitle = translate("Stop")
        self.inputstyle = "reset"
    else
        self.inputtitle = translate("Start")
        self.inputstyle = "apply"
    end

    return Button.render(self, section, scope)
end

function toggle.write()
    if running() then
        service_action("stop")
    else
        service_action("start")
    end

    luci.http.redirect(
        luci.dispatcher.build_url(
            "admin",
            "services",
            "bypass_proxy"
        )
    )
end

-- ============================================================
-- RESTART
-- ============================================================

local restart = s:option(
    Button,
    "_restart",
    translate("Restart")
)

restart.inputtitle = translate("Restart")
restart.inputstyle = "reload"

function restart.write()
    service_action("restart")

    luci.http.redirect(
        luci.dispatcher.build_url(
            "admin",
            "services",
            "bypass_proxy"
        )
    )
end

-- ============================================================
-- BOOT
-- ============================================================

local boot = s:option(
    Flag,
    "_boot",
    translate("Start at boot")
)

boot.rmempty = false
boot.enabled = "1"
boot.disabled = "0"

function boot.cfgvalue()
    return boot_enabled() and "1" or "0"
end

function boot.write(self, section, value)
    if value == "1" then
        sys.call(INIT .. " enable >/dev/null 2>&1")
    else
        sys.call(INIT .. " disable >/dev/null 2>&1")
    end
end

-- ============================================================
-- PROXY SERVER
-- ============================================================

local server = s:option(
    Value,
    "server",
    translate("Proxy Server")
)

server.datatype = "host"
server.rmempty = false
server.placeholder = "proxy.example.com"

-- ============================================================
-- PROXY PORT
-- ============================================================

local port = s:option(
    Value,
    "port",
    translate("Proxy Port")
)

port.datatype = "port"
port.rmempty = false
port.placeholder = "1080"

-- ============================================================
-- PROXY TYPE
-- ============================================================

local proxy_type = s:option(
    ListValue,
    "type",
    translate("Proxy Type")
)

proxy_type:value("socks5", "SOCKS5")
proxy_type:value("socks4", "SOCKS4")

proxy_type.default = "socks5"
proxy_type.rmempty = false

proxy_type.description = translate(
    "SOCKS5 supports username/password authentication. " ..
    "SOCKS4 does not support password authentication."
)

-- ============================================================
-- USERNAME
-- ============================================================

local username = s:option(
    Value,
    "username",
    translate("Username")
)

username.rmempty = true
username.maxlength = 255
username.placeholder = translate("Optional")

-- ============================================================
-- PASSWORD
-- ============================================================

local password = s:option(
    Value,
    "password",
    translate("Password")
)

password.password = true
password.rmempty = true
password.maxlength = 255
password.placeholder = translate("Optional")

-- ============================================================
-- LOCAL REDIRECT PORT
-- ============================================================

local local_port = s:option(
    DummyValue,
    "local_port",
    translate("Local Redirect Port")
)

function local_port.cfgvalue(self, section)
    return self.map:get(section, "local_port") or "1337"
end

local_port.description = translate(
    "Internal Redsocks redirect port."
)

-- ============================================================
-- DESTINATIONS
-- ============================================================

local destinations = s:option(
    DynamicList,
    "destination",
    translate("Proxy Destinations")
)

destinations.rmempty = false
destinations.placeholder = "203.0.113.5 or 198.51.100.0/24"

destinations.description = translate(
    "Only TCP connections to these IPv4 addresses or CIDR " ..
    "networks are redirected through the proxy."
)

function destinations.validate(self, value, section)
    local list = type(value) == "table" and value or { value }

    for _, v in ipairs(list) do
        if v and #v > 0 and not destination_ok(v) then
            return nil, translate("Invalid IPv4 address or CIDR network: ") .. v
        end
    end

    return value
end

return m
BP_CBI

# ============================================================
# ENABLE + START (only when configured)
# ============================================================

/etc/init.d/bypass-proxy enable
rm -rf /tmp/luci-*

is_running() {
    ubus call service list '{"name":"bypass-proxy"}' 2>/dev/null |
        jsonfilter -e '@["bypass-proxy"].instances.main.running' 2>/dev/null |
        grep -qx true
}

CFG_SERVER="$(uci -q get bypass_proxy.main.server)"
CFG_DESTS="$(uci -q get bypass_proxy.main.destination)"

if [ -z "$CFG_SERVER" ] || [ -z "$CFG_DESTS" ]; then
    echo
    echo "Installed, but not configured yet - the service was not started."
    echo "Open LuCI -> Services -> Bypass Proxy, set the Proxy Server and at"
    echo "least one Proxy Destination, click Save & Apply, then click Start."
    exit 0
fi

echo
echo "== Starting Bypass Proxy =="
/etc/init.d/bypass-proxy restart
sleep 2

if ! is_running; then
    echo "ERROR: Bypass Proxy did not start."
    echo "Run:  logread -e bypass-proxy"
    exit 1
fi

echo "Service: running"

echo
echo "--- Redsocks syntax ---"
if redsocks -t -c /etc/redsocks-bypass.conf >/dev/null 2>&1; then
    echo "OK"
else
    echo "ERROR"
fi

echo
echo "--- Firewall rules ---"
iptables -w -t nat -S BYPASS_PROXY 2>/dev/null

echo
echo "--- PREROUTING hook ---"
if iptables -w -t nat -C PREROUTING -i br-lan -p tcp -j BYPASS_PROXY 2>/dev/null; then
    echo "OK"
else
    echo "HOOK NOT FOUND"
fi

echo
echo "Bypass Proxy installation complete. LuCI: Services -> Bypass Proxy"
